### ISSUE TITLE
README warning clarification

### ISSUE THREAD

**Issue by cburroughs** [zuazo/ssh_authorized_keys-cookbook#1]
> Warning: This definition uses the Accumulator Pattern. This implies that any SSH key added using other methods (such as keys added by hand) will be deleted.

My general expectation when chef is templating a file is that any manual changes to that file will be overwritten when chef runs next.  What makes the Accumulator Pattern particuarly dangerous?

**Comment by zuazo** [comment]
@cburroughs, you are right.

That is a clarification to warn that the lines added by hand will be deleted. I put that note because this file can render your server inaccessible if you expect the lines added by hand continue there after the chef-run. Other similar cookbooks that also generate _authorized_keys_ files keep the lines added by hand so I thought it was important to clarify that point.

But I am completely open to change or even remove the warning if you believe that it can confuse people.

**Comment by cburroughs** [comment]
I think the part that confused me was trying to think of what 'other methods' might be besides manual edits to the file.  I was worried I had to carefully structure my recipies in some special way to accomodate the Accumulator Pattern.

Since other `authorized_keys` related cookbooks do try to preserve the hand edits a note in the README does seem reasonable.

**Comment by zuazo** [comment]
OK. What can we write in the note to make it less confusing?
